use_frameworks!

target 'JabirDemoSpec_Example' do
  pod 'JabirDemoSpec', :path => '../'

  target 'JabirDemoSpec_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
